apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: lab
kubeAPI:
  host: lab.home
  hostIP: 192.168.0.8
  hostPort: "6443"
ports:
  - port: 8443:443
    nodeFilters:
    - loadbalancer
volumes:
  - volume: /home/home/Documents/work/k3d/volumes/manifests:k3s-manifests-custom
    nodeFilters:
    - server:*
  - volume: /home/home/Documents/work/k3d/volumes/snapshots:/var/lib/rancher/k3s/server/db/snapshots
    nodeFilters:
    - server:*
  - volume: /home/home/Documents/work/k3d/volumes/storage/server:k3s-storage
    nodeFilters:
    - server:*
  - volume: /home/home/Documents/work/k3d/volumes/storage/agent:k3s-storage
    nodeFilters:
    - agent:*
servers: 1
agents: 1
options:
  runtime:
    serversMemory: 2Gi
    agentsMemory: 3Gi
  k3d: 
    wait: true
  k3s:
    extraArgs:
      - arg: --tls-san=lab.home
        nodeFilters:
        - server:* 
      - arg: --cluster-init
        nodeFilters:
        - server:0
      - arg: --secrets-encryption
        nodeFilters:
        - server:*
      - arg: --node-taint=trust=high:NoExecute
        nodeFilters:
        - agent:0
    nodeLabels:
      - label: k8s.lab.home/workload=infra
        nodeFilters:
        - agent:0
